### ISSUE TITLE
Atom Error: Unable to start the Bash language server in Windows

### ISSUE THREAD

**Issue by roblogic** [mads-hartmann/ide-bash#4]
I get these errors when starting Atom (on Windows 10), or reloading the ide-bash plugin
* "Unable to start the Bash language server, Please make sure you've followed the System Requirements section in the README"
* "BashIDE language server for Shell Script unable to start, Error: spawn bash-language-server ENOENT"

![image](https://user-images.githubusercontent.com/16142896/40822779-f068a126-65c1-11e8-9004-080a3de89ee1.png)

Set up everything correctly AFAICT ,and I have just installed the latest release of Atom (1.27.2 x64)

( this issue is forked from comments in mads-hartmann/ide-bash#2 )
( could be mitigated by mads-hartmann/ide-bash#1 )
( seems quite similar to mads-hartmann/bash-language-server#41 )

I think it's happening here in main.js. Maybe "spawn" isn't smart enough to find the npm package in windows

https://github.com/mads-hartmann/ide-bash/blob/ff7acfe95a37915ed8e1effe75df88e2b073c5e0/src/main.js#L29-L31

I found a couple of things to look into
* https://stackoverflow.com/questions/27688804/how-do-i-debug-error-spawn-enoent-on-node-js
* https://stackoverflow.com/questions/37288044/atom-electron-cant-find-path-of-child-process

**Comment by roblogic** [comment]
A couple of alternatives to existing Node spawn on windows:
* https://github.com/MarcDiethelm/superspawn
* https://www.npmjs.com/package/cross-spawn

**Comment by jason-c-daniels** [comment]
Has anyone tried??
```js
(function() {
    var childProcess = require("child_process");
    var oldSpawn = childProcess.spawn;
    function mySpawn() {
        console.log('spawn called');
        console.log(arguments);
        var result = oldSpawn.apply(this, arguments);
        return result;
    }
    childProcess.spawn = mySpawn;
})();
```
As recommended in: https://stackoverflow.com/questions/27688804/how-do-i-debug-error-spawn-enoent-on-node-js

If so, what were the results?

**Comment by mads-hartmann** [comment]
Switching to using cross-spawn seems like the best options to me.

**Comment by buchdag** [comment]
I've got the same issue on OSX 10.11.6 and Atom 1.29.0

![screen shot 2018-08-20 at 17 43 27](https://user-images.githubusercontent.com/13685826/44350882-be589880-a4a0-11e8-9802-9643d31d2ca6.png)

**Comment by hgeri95** [comment]
I've got the same issue and I found a solution on Windows. In the following directory: _C:\Users\<user>\.atom\packages\ide-bash\src_ you can find a main.js file. I changed the following line:
  _const command = 'bash-language-server.cmd'_
After this change it works for me. 

(Before this I tried **papesch** suggestions with _windows-build-tools_ and _superspawn_ from this page https://github.com/mads-hartmann/bash-language-server/issues/41 )

**Comment by aminya** [comment]
Same issue here.

> 
> 
> I've got the same issue and I found a solution on Windows. In the following directory: _C:\Users<user>.atom\packages\ide-bash\src_ you can find a main.js file. I changed the following line:
> _const command = 'bash-language-server.cmd'_
> After this change it works for me.
> 
> (Before this I tried **papesch** suggestions with _windows-build-tools_ and _superspawn_ from this page [mads-hartmann/bash-language-server#41](https://github.com/mads-hartmann/bash-language-server/issues/41) )

This should be a PR! I created one: https://github.com/mads-hartmann/ide-bash/pull/9
